receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp:
    endpoint: http://192.168.1.107:52123    
    tls:
      insecure: true

service:

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
      #exporters: [influxdb]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
      #exporters: [influxdb]


